# Generated by Django 4.1.7 on 2023-08-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=32, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='электронная почта')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='номер телефона')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('activation_code', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
